version: "3.7"

services:
  redis:
    image: redis:6
    command: redis-server --requirepass testing
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  get5db:
    image: mysql
    container_name: get5db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=testing
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=testing
    ports:
      - 3306:3306

  g5api:
    build: .
    depends_on:
      - get5db
    container_name: G5API
    ports:
      - 3301:3301
    environment:
      - NODE_ENV=production
      - PORT=3301
      - HOSTNAME=http://localhost
      - DBKEY=
      - STEAMAPIKEY=
      - SHAREDSECRET=testing
      - CLIENTHOME=http://localhost
      - APIURL=http://localhost:3301
      - SQLUSER=get5
      - SQLPASSWORD=testing
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=
      - REDISURL=redis://:testing@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=false
    restart: always

  g5v:
    image: g5v:latest
    depends_on:
      - g5api
    container_name: G5V-Front-End
    ports:
      - 80:80
    restart: always
